### ISSUE TITLE
buggy af

### ISSUE THREAD

**Issue by slashwarm** [skorom/Markdown#2]
replacer.cs can't replace words if there's no spaces after and before the word

**Comment by szgerii** [comment]
U succ

**Comment by slashwarm** [comment]
> U succ

if you cant help then stfu. this is very important you can believe me idiot

**Comment by slashwarm** [comment]
an innocent soul depends on this issue

**Comment by szgerii** [comment]
ur mum gay

**Comment by slashwarm** [comment]
ur dad lesbian

**Comment by szgerii** [comment]
ur sister a mister

**Comment by slashwarm** [comment]
ur granny tranny

**Comment by szgerii** [comment]
ur brother a mother

**Comment by slashwarm** [comment]
szeretsz időt égetni?
